.github/actions/admin/action.yml, .github/actions/apply/action.yml, .github/actions/plan/action.yml
Intentionally did not use `google-github-actions/upload-cloud-storage` so the action can comment with errors when upload fails. Composite actions cannot use conditionals to trap errors from a previous action when using upload-cloud-storage.
- Dropping gcloud saves about 190 MB in transfer time to download: https://cloud.google.com/sdk/docs/install#linux
- Adding setup-node is minimal cost as version 16 is already cached on the runner image: https://github.com/abcxyz/guardian/actions/runs/4645596462/jobs/8221519755#step:6:392
- Adding `google-cloud/storage` is ~838 kB unpacked, and should be minimal overhead as it will be most likely be zipped: https://www.npmjs.com/package/@google-cloud/storage
=> remove gcloud in favor of node cloud storage sdk

.github/actions/admin/action.yml
Some commands dont have the input flag, so removing this as a cli option.
=> remove cli args from admin

.github/actions/directories/action.yml, .github/workflows/test-admin.yml, .github/workflows/test-apply.yml, .github/workflows/test-plan.yml, README.md, examples/guardian-admin.yml, examples/guardian-apply.yml, examples/guardian-plan.yml, terraform/child/.terraform.lock.hcl, terraform/child/main.tf, terraform/child/terraform.tf
Adds the ability to detect git changes and only run guardian for those directories. 
A workflow job will be used to look for all terraform files with a `backend ".*" {` syntax. If a file exists in a directory with this syntax, it will be considered the root of a module and will be a target for plan/apply.
A second step will look for what files have changed and create the intersection between changed directories and the root directories.
=> add change detection to limit plans/applies

.github/actions/apply/action.yml, .github/actions/hide-plan-comments/action.yml, .github/actions/plan/action.yml, .github/workflows/test-plan.yml, examples/guardian-plan.yml, terraform/child/main.tf, terraform/main.tf
Implemented an action to hide previous PR run comments. This is to help clean up PRs with multiple plan runs. Created as an action to provide opt-in functionality.
=> add action to hide previous plan comments

.github/actions/admin/action.yml, .github/actions/apply/action.yml, .github/workflows/test-admin.yml, examples/guardian-admin.yml, terraform/main.tf
fixes #81 - Prevent users from triggering a re-run of the apply command after merge
fixes #80 - Allow users to prevent running terraform init on admin operations
=> prevent apply re-runs and allow admin to prevent terraform init command

.github/actions/apply/action.yml, terraform/main.tf
Bootstrapping error file should come first, otherwise the following steps will fail.
=> adjust apply workflow ordering for errors

.github/actions/admin/action.yml
This will be used to create workflows that could allow users with write access to run one off plan or apply workflows from the main branch. This allows for flexibility in administering a terraform repo via automation.
=> add flag to allow non-admin users to run admin commands

pkg/commands/drift/command.go
Currently the output is incorrectly formatted:
=> fix(drift): Output message for both click ops and missing tf changes

pkg/commands/drift/drift.go, pkg/commands/drift/drift_test.go, pkg/storage/google_cloud_storage.go, pkg/storage/storage.go, pkg/storage/storage_mock.go, pkg/terraform/parser/parser.go, pkg/terraform/parser/parser_test.go
Fails to download subsequent TF state files because the ctx::Cancel() was already called.
=> fix(drift): Context cancelled issue

.github/actions/iam-drift-detection/action.yml, pkg/commands/drift/command.go, pkg/commands/drift/github.go, pkg/github/github.go
GitHub Issues do not support assigning to Teams. Instead you must mention them.
fix(drift): Init map for GitHub Issue List method
Tested: https://github.com/theteamatx/x-refinery-org/issues/206
=> feat(drift): Support appending arbitrary message

pkg/commands/plan/plan_run.go, pkg/commands/plan/plan_run_test.go
Apply reads the plan file and metadata to determine if it should apply, we should always upload the plan file even if no changes.
=> fix: always upload plan regardless of changes for apply to read

cmd/guardian/main.go, go.mod, go.sum, pkg/assetinventory/assetinventory.go, pkg/assetinventory/assetinventory_mock.go, pkg/commands/drift/command.go, pkg/commands/drift/drift.go, pkg/commands/drift/drift_test.go, pkg/commands/drift/driftignore.go, pkg/commands/iamcleanup/command.go, pkg/commands/iamcleanup/iamcleanup.go, pkg/commands/iamcleanup/iamcleanup_test.go, pkg/iam/iam.go, pkg/iam/iam_mock.go, pkg/iam/iam_test.go, pkg/terraform/parser/parser.go, pkg/terraform/parser/parser_test.go
Fixes https://github.com/abcxyz/guardian/issues/145
I've manually tested this by running against X's org which had outdated AOD requests and it successfully deleted all expired IAM.
```
GUARDIAN_LOG_LEVEL=debug go run ./cmd/guardian iam-cleanup --scope=organizations/XXXXXXXX --iam-query="policy:abcxyz-aod-expiry"
```
=> feat(iam-cleanup): Add new subcommand for cleaning up IAM

.github/workflows/test-admin.yml, .github/workflows/test-apply.yml, pkg/commands/plan/plan_init.go, pkg/commands/plan/plan_init_test.go, pkg/commands/plan/plan_run.go, pkg/commands/plan/plan_run_test.go
- Plan run now handles correct output formatting for non-actions
- Added `-skip-detect-changes` flag for plan init, this is useful for running a for the entire entrypoint universe.
=> fix(plan): run handles non action environments, init add skip changes

go.mod, go.sum, pkg/commands/drift/command.go, pkg/commands/iamcleanup/command.go, pkg/commands/plan/plan_init.go, pkg/commands/plan/plan_run.go
This will inherit the new features in the CLI onto the flag set, such as overriding the environment.
=> Get flagset from the CLI

pkg/terraform/apply.go, pkg/terraform/apply_test.go, pkg/terraform/init.go, pkg/terraform/init_test.go, pkg/terraform/plan.go, pkg/terraform/plan_test.go, pkg/terraform/run.go, pkg/terraform/show.go, pkg/terraform/show_test.go, pkg/terraform/terraform.go, pkg/terraform/terraform_mock.go, pkg/terraform/validate.go, pkg/terraform/validate_test.go
This will allow for a future commands that can execute supplied terraform commands. The idea is to enable the ability to create admin or helper workflows that can run a limited set of terraform commands for administering terraform from github workflows.
Examples:
- I want to run terraform force-unlock to remove the lock from a failed run
- I want to run terraform apply again to fix the previous failed run
- I want to list the outputs for a given module
=> chore: refactor terraform package to use a common run command

cmd/guardian/main.go, pkg/commands/initialize/config.go, pkg/commands/initialize/config_test.go, pkg/commands/initialize/init.go, pkg/commands/initialize/init_test.go, pkg/commands/plan/config.go, pkg/commands/plan/config_test.go, pkg/commands/plan/plan_run.go, pkg/commands/run/run.go, pkg/commands/run/run_test.go, pkg/github/github.go, pkg/github/github_mock.go, pkg/terraform/terraform_mock.go
Closes #152 
Adds new functionality to the init command to validate github actor permission levels for the repository. This is useful when a repository administrator wants to create a more powerful workflow that can run sensitive commands to administer terraform, but wants to restrict it to repo admins or specific repo permission levels.
Adds a new run command that can run arbitrary terraform sub commands. This also adds the ability to restrict which commands are allowed to be run. This is useful when running in a github workflow for workflow_dispatch so repository admins can create a workflow that can only run a subset of commands for users to administer failures.
NOTE: all of this works and is secure because the workflow is run from main, so only administrators can create workflows and …
=> feat: create run command to replicate guardian admin functionality

cmd/guardian/main.go, pkg/commands/entrypoints/entrypoints.go, pkg/commands/entrypoints/entrypoints_test.go, pkg/commands/entrypoints/testdata/backends/project1/main.tf, pkg/commands/entrypoints/testdata/backends/project2/main.tf, pkg/commands/entrypoints/testdata/no-backends/project1/main.tf, pkg/commands/entrypoints/testdata/no-backends/project2/main.tf
The command `initialize` seems to being doing too much and is confusing. It currently mixes core logic (finding entrypoints) with GitHub specific logic (deleting PR comments, required permissions, etc).
This PR is one of multiple PRs that will split this logic apart.
In this PR, the logic related to determining the Guardian entrypoints is moved to its own command. The follow up PRs will create a new command for handling GitHub specific logic.
=> chore: refactor the part of init into entrypoints

pkg/commands/plan/plan_run.go, pkg/commands/plan/plan_run_test.go, pkg/commands/workflows/config.go, pkg/commands/workflows/config_test.go, pkg/commands/workflows/plan_status_comments.go, pkg/commands/workflows/plan_status_comments_test.go, pkg/commands/workflows/remove_plan_comments.go, pkg/commands/workflows/validate_permissions.go, pkg/commands/workflows/validate_permissions_test.go
Migrate the existing plan-status action to the workflows command. This command is used by a github workflow as a post status job. The users can configured required status checks to ensure this check is required because when using a matrix strategy, the plan job has dynamic names and makes it impossible to have required status checks for all possible directories.
This change also cleans up required flags for several commands and adds tests for them.
=> feat: migrate plan-status to go

pkg/commands/apply/apply_run.go, pkg/commands/apply/apply_run_test.go
- Terraform apply needs the full path to the plan file in the temp dir
- Renamed `planFilename` -> `planFileName`
=> fix: guardian apply plan file path

pkg/git/git.go, pkg/git/git_test.go, pkg/util/util.go, pkg/util/util_test.go
The previous fix didn't account for only deleting a single file, which would still require the directory to be plan/applied.
In this solution, if a whole directory is deleted, and the directory cannot be found, it will be ignored.
=> fix: ignore deleted dirs for git diff

pkg/commands/drift/statefiles/statefiles.go
Some infra repos store state in multiple different buckets. Statefile drift detection should find all uris in all buckets referenced in terraform configuration.
Tested it against X's repo for their gcp-org which has many backend buckets.
=> feat: allow running statefile drift on repo with different backends

pkg/commands/drift/github.go, pkg/commands/drift/statefiles/statefiles.go, pkg/git/git.go, pkg/git/git_mock.go, pkg/github/github.go, pkg/github/github_mock.go
These change updates statefile drift so that it 
* Clones all github repositories that have a given set of topics (e.g. terraform, guardian) - this will be limited by the github token passed - so if you only have access to 1 repo you will only get 1 repo.
* (noop) Determines all expected statefile locations in gcs using the method already used
* Fetches all gcs buckets - this will be limited by the access that you/your SA has.
* (noop) Determines all actual statefile locations in gcs using the method already used
To support environments that don't have elevated github permissions I introduced a new flag called `detect-gcs-buckets-from-terraform` that will not rely on fetching GCS buckets from the asset inventory API. Instead it will parse them from the terraform configuration (this is how …
=> feat: update statefile drift to check all repos and buckets

internal/version/version.go, pkg/child/child.go, pkg/child/child_test.go, pkg/commands/drift/command.go, pkg/commands/drift/drift.go, pkg/commands/drift/driftignore.go, pkg/commands/iamcleanup/command.go, pkg/commands/iamcleanup/iamcleanup.go, pkg/terraform/terraform.go
This also sets us up for a future world where we can allow/deny specific environment variables from the parent process (such as forbidding users to override the path to a terraformrc file).
=> Inject custom user-agent headers

pkg/commands/drift/statefiles/statefiles.go, pkg/terraform/parser/parser.go
This enables statefiles drift detection to inform the user which statefiles that were found are actually empty (result of an init without an apply)
Example of new output:
```
Found state locally that are not in remote
> gs://terraform-abc123/terraform/a/default.tfstate
> gs://terraform-abc123/terraform/b/default.tfstate
Found statefiles in remote that are not in local           
> gs://terraform-abc123/terraform/c/default.tfstate
> gs://terraform-abc123/terraform/d/default.tfstate
Found empty statefiles in remote that are not in local
> gs://terraform-abc123/terraform/e/default.tfstate
> gs://terraform-abc123/terraform/f/default.tfstate
```
=> feat: designate which statefiles are empty in drift detection

guardian.env.yml
`guardian.env.yml` is no longer needed as these environemnt variables are now set directly by the `.github/workflows/integration.yml` workflow, and it is now the only workflow that needs these environment variables.
=> Remove unneeded guardian.env.yml

pkg/commands/plan/plan_run.go
* Add `-no-color` flag to when executing Terraform Fmt to avoid colors in ouput
* Refactor `updateResultCommentForActions()` to reduce redundant code
=> Add -no-color flag to Terraform Fmt

pkg/commands/plan/plan_run.go, pkg/commands/plan/plan_run_test.go
* Ensure Guardian does not exceed GitHub's comment length limit when making comments. If the message exceeds the maximum length, it is truncated and a sentence is added to the end indicating that the full message can be viewed in the workflow logs.
closes #238
=> Limit Guardian GitHub comment length

.github/workflows/integration.yml, cmd/guardian/main.go, pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go
* `guardian plan run $ARGS` -> `guardian plan $ARGS`
* `guardian apply run $ARGS` -> `guardian apply $ARGS`
* Refactored names of structs and files for `plan` and `apply` commands to reflect the removal of `run` subcommand.
=> Simplify `plan` and `apply` commands

pkg/commands/plan/plan.go, terraform/project1/main.tf
* Fixed a bug where `terraform fmt` can respond with a non-zero
exit code but still write its ouput to `stdout` instead of `stderr`.
Fix checks `stderr` first for output and if that is empty it falls
back to `stdout` for determining the output.
closes #258
=> Fix bug where formatting error does not display

cli.md
Specify which GitHub permissions are needed explicitly for each the guardian CLI commands.
=> Document cli GitHub permission commands

README.md
* Switched to recommend Rulesets instead of branch protection.
* Cleaned up references from `plan-run`/`apply-run` to `plan`/`apply`
=> Recommend Rulesets instead of Branch Protection

cli.md, pkg/commands/apply/apply.go, pkg/commands/drift/statefiles/statefiles.go, pkg/commands/entrypoints/entrypoints.go, pkg/commands/plan/plan.go, pkg/commands/run/run.go, pkg/commands/workflows/plan_status_comments.go, pkg/commands/workflows/remove_comments.go
* Switched to using the `-dir` flag for the `drift statefiles` command to make it consistent with other commands.
* Cleaned up 'Usage' strings that implied a different of method of input for directory or pull request number for various commands.
=> Switch `drift statefiles` to use `-dir` flag

pkg/commands/actions/actions.go, pkg/commands/actions/actions_test.go, pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/commands/run/run.go, pkg/commands/run/run_test.go
* Created a base `GitHubActionCommand` that implements the `WithActionsOutGroup` method. Any command that wants this functionality can simply embed this struct.
* Refactored `PlanCommand`, `ApplyCommand`, and `RunCommand` to use the new `GitHubActionCommand`.
closes #185
=> Add base `GitHubActionCommand`

abc.templates/drift-workflows/spec.yaml
This fixes the indentation of the spec file used for rendering drift-workflows
Fixes #293
=> fix drift-workflows abc.template

abc.templates/drift-workflows/contents/guardian-drift-detection.yml
This makes the version of `actions/checkout` consistent across all workflow templates
=> Update pinned actions/checkout for drift workflow

pkg/terraform/parser/parser.go, testdata/test_valid.tfstate
This fixes an issue where parsing the Terraform statefile would error during drift detection. See #317 for more details.
=> fix: drift detection parsing issue

cli.md, cmd/guardian/main.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/util/util.go
Fixes #325. This helps avoid a situation where a terraform codebase accumulates lots of technical debt. The command `guardian plan -fail-on-diff` can be run in a cron job. As soon as cloud resources differ from their declared desired state in terraform (due to, say, some scoundrel clicking in the cloud console), then you'll know shortly thereafter instead of silently diverging for some unknown amount of time.
=> feat: add a flag to optionally fail if `plan` finds a diff

pkg/commands/drift/statefiles/statefiles.go, pkg/storage/google_cloud_storage.go, pkg/terraform/parser/parser.go
I am seeing a [failure](https://github.com/theteamatx/x-refinery-org/actions/runs/9500936795/job/26185227984) caused by running `guardian drift statefiles` when asset inventory returns a gcs bucket that is in a recently deleted project. We should check whether a bucket exists and skip ones that don't exist.
=> fix: handle bucket not found error

pkg/assetinventory/assetinventory.go, pkg/assetinventory/assetinventory_mock.go, pkg/commands/drift/drift.go, pkg/commands/drift/drift_test.go, pkg/commands/iamcleanup/iamcleanup.go
This change leverages Cloud Asset Inventory API to reduce the number of req/min. The previous behavior would invoke the resourcemanager API once per project and folder in the organization but now it will call CAI based on the number of IAM resources / page_size.
Note, `asset.SearchAllIamPolicies` will also include IAM policies of projects and folders in `DELETE_REQUESTED` state, so in a follow up, we should call CAI to fetch all the projects in `DELETE_REQUESTED` state and exclude them using the query for `asset.SearchAllIamPolicies`.
=> Use CAI to fetch IAM policies in IAM detect-drift

cli.md, cmd/guardian/main.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/util/util.go
This reverts commit https://github.com/abcxyz/guardian/commit/d88f16193d6d5f1cd66b50bd34ab7fbc2c192517.
This was the wrong way to accomplish my intent. The nightly cron job will use `guardian run plan` rather than `guardian plan`, so this whole feature was misguided.
=> Revert "feat: add a flag to optionally fail if plan finds a diff" in PR #326

abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-admin.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-apply.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-plan.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-run.yml, abc.templates/drift-workflows/testdata/golden/basic/data/.github/workflows/guardian-drift-detection.yml
The release is https://github.com/google-github-actions/auth/releases/tag/v2.1.3. This was already used in some places in this repo, but not everywhere. This PR updates every place in this repo where this action is used.
=> update to latest gcp auth action

.github/workflows/integration.yml, abc.templates/base-workflows/testdata/golden/basic/test.yaml, abc.templates/drift-workflows/testdata/golden/basic/test.yaml, pkg/commands/entrypoints/entrypoints.go, pkg/commands/entrypoints/entrypoints_test.go, pkg/flags/common.go, pkg/modifiers/modifiers.go, pkg/modifiers/modifiers_test.go, pkg/terraform/testdata/with-modules/modules/module-a/main.tf, pkg/terraform/testdata/with-modules/modules/module-b-using-a/main.tf, terraform/project1/main.tf, terraform/project2/main.tf
Adding the ability to detect removed directories and if a user supplied meta comment of `GUARDIAN_DESTROY=terraform/backends/project1` exists, the supplied directory will be planned and applied as a destroy instead.
This functionality only cover the `entrypoints` command to identify the appropriate directories. The output of this command is a breaking change, as the JSON output has additional fields to support the modified and destroyed directories.
The follow up to this will be to implement the functionality in the plan and apply commands to us the destroy flag.
NOTE: Some of the test data files just had a license header added and can be ignored.
GUARDIAN_DESTROY=terraform/project2
=> feat: add destroy functionality

.github/workflows/integration.yml, abc.templates/base-workflows/contents/guardian-apply.yml, abc.templates/base-workflows/contents/guardian-plan.yml, pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/github/github.go, pkg/github/github_mock.go
Context: https://github.com/abcxyz/guardian/issues/179
Make Guardian github comment log links go directly to the logs for the relevant job instead of to the summary page when possible.
=> Link directly to logs for job in Guardian github comments

.github/workflows/integration.yml, pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/commands/workflows/plan_status_comments.go, pkg/commands/workflows/plan_status_comments_test.go, pkg/terraform/plan.go, pkg/terraform/plan_test.go, pkg/util/util.go, pkg/util/util_test.go
Open to suggestions on the output formatting. The integration workflow is not representative of what the end state will look like in production.
Actual flow:
```
init
-> modified or "just plan" directories
-> destroy or plan -destroy directories
plan
business as usual for modified dirs
plan-destroy
checkout main
guardian plan with -destroy flag
PR MERGED
init
-> modified or "just plan" directories
-> destroy or plan -destroy directories
apply
business as usual for modified dirs
apply-destroy
checkout HEAD-1 (`github.events.pull_request.before`)
guardian apply (parse destroy from GCS plan file metadata)
```
* Checking out main/head-1 is needed because we potentially deleted the directory or want to delete all existing resources.
* Splitting the jobs allows us to customize per operation …
=> feat: complete destroy

.github/workflows/integration.yml, pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/cleanup/cleanup.go, pkg/commands/cleanup/cleanup_test.go, pkg/commands/drift/statefiles/statefiles.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/storage/filesystem_storage.go, pkg/storage/google_cloud_storage.go, pkg/storage/google_cloud_storage_test.go, pkg/storage/options.go, pkg/storage/storage.go, pkg/storage/storage_mock.go, pkg/terraform/parser/parser.go
Trying to abstract the storage interface even further. Eventaully, Guardian should run locally with the filesystem storage and write the plan to local filesystem. For now, these changes are in preparation of that.
* Renamed interface functions that arent specific to network requests, eg download
* Updated references to functions
* Created new filesystem storage impl
=> feat: add filesystem storage impl

pkg/flags/global.go
This change helps provide context about which CI/CD environment a Guardian command is running in. This is useful for determining which client implementations to initialize.
=> Add Platform flag to new GlobalFlags section

pkg/github/github.go
This is a generalized version of the TokenSource function, which we will need frequently when instantiating new GitHub clients. The previous implementation tied us to generating `TokenSource`s from `flags.GitHubFlags`
=> Add TokenSource function to github package

pkg/platform/github.go, pkg/platform/platform.go
This creates a new GitHub type to implement the Platform interface. All the methods of the GitHub interface in `github.com/abcxyz/guardian/pkg/github` will be moved to the Platform interface/package.
=> Create new GitHub implementation of Platform interface

pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/terraform/terraform_mock.go
This change writes the plan to a JSON file, in addition to the existing plan binary, so that it can be parsed by other commands (specifically the `policy` command). 
Added a new `output-dir` flag to specify the directory that plan binary and json files are written to. This is helpful for writing to temp directories in unit tests, so that any written files are cleaned up after running unit tests.
=> Save plan file as JSON file in plan command

.github/workflows/integration.yml, pkg/child/child.go, pkg/commands/apply/apply.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/commands/run/run.go, pkg/terraform/run.go, pkg/terraform/terraform.go
Also removed the override env vars from the child process to being passed in by the caller.
/cc @gjonathanhong
=> fix: cleanup plan command

cmd/guardian/main.go, pkg/commands/policy/fetch_data.go, pkg/commands/policy/fetch_data_test.go, pkg/commands/policy/flags.go, pkg/platform/github.go, pkg/platform/local.go, pkg/platform/platform.go, pkg/platform/platform_mock.go
This command fetches data used as context for policy evaluation and writes it to a local file named `guardian_policy_context.json`. It currently only aggregates the pull request approvers data.
=> Add policy fetch-data command

README.md
As a follow-up, we should add examples files under an `examples` folder, to demonstrate
- what a valid Rego policy looks like for Guardian
- how to add this in the Guardian Plan workflow.
=> Add initial policy enforcement documentation

pkg/reporter/github_reporter.go, pkg/reporter/github_reporter_test.go, pkg/reporter/reporter.go
This change moves helper methods and common types out from `github_reporter.go` to `reporter.go`. They were previously tied to the GitHubReporter type, but made more sense as common types/methods that shouldn't change between platforms. This will allow us to generate status messages that are consistent across different code review platforms, instead of reimplementing them each time.
=> refactor: generalize status message helpers for Reporter types

pkg/reporter/file_reporter.go, pkg/reporter/reporter.go
This change provides an option to report the status or entrypoints summary comment to a local file on disk.
=> Add FileReporter

pkg/commands/policy/fetch_data_test.go, pkg/github/config.go, pkg/platform/github.go, pkg/platform/local.go, pkg/platform/platform.go, pkg/platform/platform_mock.go
This change adds `GetUserRepoPermissions` to the Platform interface, which adds the user's access level for a repository as additional context in policy evaluations. This also changes `platform.GetPolicyData()` to skip fetching Pull Request Approvers if a pull request number is not provided.
```javascript
{
github: {
pull_request_approvers: {
// ...
},
user_access_level: "admin",
}
}
```
=> Add UserAccessLevel in GetPolicyData result

pkg/commands/policy/enforce.go, pkg/commands/policy/enforce_test.go, pkg/commands/policy/testdata/deny.json, pkg/commands/policy/testdata/deny_all.json
This change introduces a `deny` policy, which will do nothing, block the status and print a detailed message. This also refactors the `missing_approvals` enforcement into `EnforceMissingApprovals` function, for better readability and error handling.
=> Add deny policy enforcement

pkg/commands/policy/fetch_data_test.go, pkg/platform/github.go, pkg/platform/local.go, pkg/platform/platform.go, pkg/platform/platform_mock.go
This includes a refactoring of the team memberships query, which was originally embedded inside `GetLatestApprovers`, into its own Platform interface method, `GetTeamMemberships`. This is to expose the team membership mappings of an organization in the result of the `guardian policy fetch-data` command, under the `github.team_memberships` key, so that the team memberships can be reused for writing policy definitions.
=> Add a GitHub Organization's team memberships in policy fetch-data subcommand

pkg/commands/policy/fetch_data_test.go, pkg/platform/github.go, pkg/platform/platform_mock.go
Reformats the structure of the data from:
```
{
"github": {
"user_access_level": "write"
}
}
```
To:
```
{
"github": {
"actor": {
access_level: "write",
username: "actor-username"
}
}
}
```
=> Add `actor` object in policy data

pkg/commands/policy/fetch_data_test.go, pkg/platform/github.go, pkg/platform/local.go, pkg/platform/platform.go, pkg/platform/platform_mock.go
This change improves the structure of the data available for authoring new policies. 
Now, the user's teams are included in the payload of the `github.actor`, instead of previously all teams and members of the org.
```
{
"github": {
"actor": {
"username": "abcdefg",
"teams": ["team1", "team2"]
}
}
}
```
To make this possible, instead of a single big query, `GetTeamMemberships` was refactored into `GetUserTeamMemberships`, invoked once per user.
=> refactor: Policy Fetch-Data command returns only teams that the user is a member of

pkg/commands/policy/fetch_data_test.go, pkg/github/config.go, pkg/platform/github.go, pkg/platform/platform.go, pkg/platform/platform_mock.go
The default is to exclude teams data because fetching team memberships requires additional permissions that the workflow token cannot access.
=> add include-teams flag to optionally include team data in policy fetch-data result

pkg/platform/github.go
There was a bug that ended up returning all teams in the organization as the teams the github actor is a member of. This properly returns only the teams they are members of, both direct and inherited.
=> fix: return only teams actor is a member of

pkg/commands/policy/enforce.go, pkg/commands/policy/flags.go
This will report the status of violations found but skip all actionable items, e.g. assigning reviewers.
=> Rename `--dry-run` flag to `--silent`

pkg/github/config.go, pkg/platform/github.go, pkg/platform/gitlab.go, pkg/platform/local.go, pkg/platform/platform.go, pkg/platform/platform_mock.go, pkg/platform/reporter.go
This change is part of a multi-PR change to migrate all Reporter functionality to the Platform interface. 
The motivation is to report based on the platform type, instead of allowing a mix and match between the platform type and reporter type. This will also help avoid cyclical dependencies stemmed from sharing configs.
=> Add CommentStatus to Platform interface with GitHub implementation

pkg/platform/github.go
This is mostly duplicate code from the GitHubReporter and `pkg/github` package that will now live in the Platform interface.
=> Add job logs

pkg/reporter/reporter.go
This fixes a bug where all plan comments without diffs do not display details in a code block.
=> Add codeblock to non-diff comments

pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/platform/reporter.go, pkg/reporter/reporter.go
This change adds the error message back to the plan comment, for tracing the source of the failure.
=> Add error message to plan comments

cli.md, pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/github/config.go
This updates the CLI documentation to reflect the new flag names and options for version `>= v2.0.4`. This also removes an unused `destroy` flag in the `plan` and `apply` commands.
=> Update documentation for CLI commands and remove unused `-destroy` flag in `plan` and `apply` commands

pkg/commands/apply/apply.go, pkg/commands/apply/apply_test.go, pkg/commands/entrypoints/entrypoints.go, pkg/commands/entrypoints/entrypoints_test.go, pkg/commands/plan/plan.go, pkg/commands/plan/plan_test.go, pkg/commands/policy/enforce.go, pkg/commands/policy/enforce_test.go, pkg/commands/workflows/plan_status_comments.go, pkg/commands/workflows/plan_status_comments_test.go, pkg/commands/workflows/remove_comments.go, pkg/platform/platform_mock.go
The platform client now implements all of the reporter's functions. This change migrates all of the commands to use the platform's implementation of reports instead of the reporter package's implementation. The reporter will be removed completely in a follow-up.
=> Decouple reporter from all commands and replace with platform client

go.mod, go.sum, pkg/platform/config.go, pkg/platform/gitlab.go, pkg/platform/reporter.go
This change defines two sets of configs, one used for Guardian command flags and the other for loading the default predefined GitLab variables that are injected in the environment in CI pipelines. These values are used to instantiate the GitLab client and make API calls to the target GitLab instance for writing notes on a merge request.
=> Add GitLab client and `GitLab.ReportStatus` implementation

pkg/platform/gitlab.go
There are two types of ID's for merge request, `CI_MERGE_REQUEST_ID` for instance-level and `CI_MERGE_REQUEST_IID` for project-level.  
According to GitLab's predefined variables documentation, 
> The project-level IID...is the number used in the merge request URL
=> fix: use merge request internal ID for GitLab API

pkg/github/github.go, pkg/platform/github.go, pkg/platform/gitlab.go, pkg/platform/local.go, pkg/platform/platform.go, pkg/platform/platform_mock.go
This method is required for Guardian Apply to report its status on a change request. For GitHub and Guardian, the PR/MR ID will not be available from the GitHub Action/GitLab Pipeline environment when merging, so the ID needs to be looked up based on the SHA of the commit.
=> Add ListChangeRequestsByCommit skeleton to Platform interface

pkg/assetinventory/assetinventory_test.go, pkg/child/child_test.go, pkg/commands/apply/apply_test.go, pkg/commands/cleanup/cleanup_test.go, pkg/commands/drift/drift_test.go, pkg/commands/entrypoints/entrypoints_test.go, pkg/commands/iamcleanup/iamcleanup_test.go, pkg/commands/plan/plan_test.go, pkg/commands/policy/enforce_test.go, pkg/commands/policy/fetch_data_test.go, pkg/commands/run/run_test.go, pkg/commands/workflows/plan_status_comments_test.go, pkg/git/git_test.go, pkg/iam/iam_test.go, pkg/storage/google_cloud_storage_test.go, pkg/terraform/apply_test.go, pkg/terraform/format_test.go, pkg/terraform/init_test.go, pkg/terraform/parser/parser_test.go, pkg/terraform/plan_test.go, pkg/terraform/show_test.go, pkg/terraform/terraform_test.go, pkg/terraform/validate_test.go, pkg/util/util_test.go
This is no longer required as of Go 1.22+
=> Remove shadowed loop variables

.github/workflows/draft-release.yml
The next version tag doesn't exist yet, we need to use the current sha from the workflow branch as the diff for generating release notes.
=> fix: draft release sha

abc.templates/base-workflows/contents/workflows/guardian-plan.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-plan.yml
This fixes the intermittent issue where guardian plan includes changes that were merged to the main branch (and are not included in your PR feature branch).
=> chore: update plan entrypoints check

README.md, abc.templates/base-workflows/contents/workflows/guardian-merge-check.yml, abc.templates/base-workflows/contents/workflows/guardian-plan.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-merge-check.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-plan.yml
See the README changes for full details of what this entails.
I decided to add the merge check to the default set of template workflows since it does not conflict and will only run if you enable the merge queue (note that it will show up as `skipped` on all pull requests).
Note that this change has been tested in https://github.com/abcxyz/infra-gcp/blob/main/.github/workflows/guardian-merge-check.yml
🤖  Also note that the description of the merge queue in the readme was mostly generated with AI.
=> feat: add merge queue check

.github/workflows/ci.yml
Updating so that we use the lint.yml workflow from pkg https://github.com/abcxyz/pkg/blob/main/.github/workflows/lint.yml. This workflow is required via an org ruleset so that it runs on this repo.
=> chore: remove lint workflows

pkg/github/config.go, pkg/platform/github.go
Currently, Guardian is configured to only call the GitHub SaaS API so it can only be run on GitHub Actions within the GitHub.com. This change exposes some options to modify the GitHub base URLs so that it can support GitHub Enterprise instances. Most of these will be inferred from the GitHub Actions environment from the default environment variables set by GitHub.
=> Allow configuring the base URL of GitHub Enterprises

.github/workflows/ci.yml, abc.templates/base-workflows/contents/workflows/guardian-admin.yml, abc.templates/base-workflows/contents/workflows/guardian-apply.yml, abc.templates/base-workflows/contents/workflows/guardian-merge-check.yml, abc.templates/base-workflows/contents/workflows/guardian-nightly.yml, abc.templates/base-workflows/contents/workflows/guardian-plan.yml, abc.templates/base-workflows/contents/workflows/guardian-run.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-admin.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-apply.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-merge-check.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-nightly.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-plan.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-run.yml, abc.templates/base-workflows/testdata/golden/basic/data/policy/guardian/admin/workflow_permissions.rego, abc.templates/drift-workflows/contents/guardian-drift-detection.yml, abc.templates/drift-workflows/testdata/golden/basic/data/.github/workflows/guardian-drift-detection.yml
This new workflow 
* Renders the guardian workflows and runs ratchet and actionlint against them. 
* Also checks the abc goldens
NOTE: This workflow will stick around even after we move to the lint.yml for ratchet and actions.
=> chore: add linting for template workflows

.github/workflows/release.yml
This change proposes a fix to address the [broken release workflow](https://github.com/abcxyz/guardian/actions/runs/14525816461/job/40757050540#step:5:34) due to recent [linting updates](https://github.com/abcxyz/guardian/pull/526).
=> fix broken release workflow

abc.templates/base-workflows/contents/workflows/guardian-admin.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-admin.yml
Parse input as array in order to correctly escape.
=> chore: update default arrayification for guardian admin

abc.templates/base-workflows/contents/workflows/guardian-admin.yml, abc.templates/base-workflows/contents/workflows/guardian-apply.yml, abc.templates/base-workflows/contents/workflows/guardian-merge-check.yml, abc.templates/base-workflows/contents/workflows/guardian-plan.yml, abc.templates/base-workflows/contents/workflows/guardian-run.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-admin.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-apply.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-merge-check.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-plan.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-run.yml, abc.templates/drift-workflows/contents/guardian-drift-detection.yml, abc.templates/drift-workflows/testdata/golden/basic/data/.github/workflows/guardian-drift-detection.yml
This change updates all pinned workflows using `ratchet` CLI. 
This also changes the setup-binary action source from the old location, `abcxyz/pkg` repository, to the actively maintained location, `abcxyz/actions` repository. Most notably, the setup-binary action from `abcxyz/pkg` relies on a deprecated version of the `actions/cache` dependency, which is now updated in the `abcxyz/actions` version. This should fix https://github.com/abcxyz/guardian/issues/537.
Commands:
```
ratchet update abc.templates/base-workflows/contents/workflows/guardian-admin.yml
ratchet update abc.templates/base-workflows/contents/workflows/guardian-apply.yml
ratchet update abc.templates/base-workflows/contents/workflows/guardian-merge-check.yml
ratchet update …
```
=> Update templates to use setup-binary action from abcxyz/actions repository

abc.templates/base-workflows/contents/workflows/guardian-admin.yml, abc.templates/base-workflows/contents/workflows/guardian-run.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-admin.yml, abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-run.yml
This updates the abc.templates with the newer `-skip-reporting` flag for commands that run outside the context of a pull request and don't need a report via PR comment. This flag used to exist as `-reporter=none` but has been deprecated since `v3.0.0+`.
=> Fix abc.templates by replacing deprecated `-reporter=none` flag with `-skip-reporting` flag
