abcxyz/guardian

.github/actions/iam-drift-detection/action.yml
.github/workflows/test-iam-drift-detection.yml
iam-drift-detection/README.md
iam-drift-detection/detect_drift.sh
iam-drift-detection/get_iam.sh
iam-drift-detection/parse_iam_from_tf_state_file.sh

Use actions/github-script instead.
Tested here: https://github.com/theteamatx/x-refinery-org/pull/158

refactor(iam-drift): Remove third party action for issues.

---

pkg/cli/detect-iam-drift.go
pkg/drift/drift.go
pkg/drift/terraform/terraform.go

Fixes #99 and also addresses comments from Dave in previous PR.

feat(drift): Add driftignore functionality

---

pkg/drift/gcs/gcs.go
pkg/drift/terraform/terraform.go

Do streaming json decoding

---

pkg/drift/assets/assets.go
pkg/drift/assets/assets_test.go
pkg/drift/drift.go
pkg/drift/driftignore.go
pkg/drift/terraform/terraform.go

Requested by @mmaraya in order to start using.
Tested: https://github.com/theteamatx/x-refinery-org/pull/158 (created issue: https://github.com/theteamatx/x-refinery-org/issues/181)

feat(drift): Allow using project name in driftignore and show in output

---

pkg/drift/drift.go
pkg/drift/driftignore.go

* feat(drift): Ignore default IAM memberships for projects
* feat(drift): Support filtering roles
Tested: https://github.com/tidaltech/gcp-org/pull/258

feat(drift): Ignore default IAM memberships for projects AND support filtering roles

---

pkg/child/child.go
pkg/child/child_test.go
pkg/terraform/terraform.go

fix: address previous pr comments

---

go.mod
pkg/storage/google_cloud_storage.go
pkg/storage/google_cloud_storage_test.go
pkg/storage/options.go
pkg/storage/storage.go
pkg/storage/storage_mock.go

@dcreey needs this for iam-drift to create single shared package.

feat: add storage package

---

pkg/commands/drift/drift.go
pkg/commands/drift/drift_test.go
pkg/storage/google_cloud_storage.go
pkg/storage/storage.go
pkg/storage/storage_mock.go
pkg/terraform/parser/parser.go
pkg/terraform/parser/parser_test.go

Close context as part of Closer

---

.github/actions/apply/action.yml
.github/actions/hide-plan-comments/action.yml
.github/actions/plan-status/action.yml
.github/workflows/test-plan.yml
go.mod
go.sum
pkg/commands/plan/command.go
pkg/commands/plan/config.go
pkg/commands/plan/config_test.go
pkg/commands/plan/plan.go
pkg/commands/plan/plan_test.go
pkg/github/github_mock.go
pkg/terraform/apply_test.go
pkg/terraform/init_test.go
pkg/terraform/plan_test.go
pkg/terraform/show_test.go
pkg/terraform/validate_test.go

- Decided to use buffer instead of file and reset it after each run. The output written to the buffer should be minimal.

feat: guardian plan

---

pkg/storage/google_cloud_storage.go

Closes https://github.com/abcxyz/guardian/issues/140

Apply gzip compression to uploaded objects

---

.github/actions/iam-drift-detection/action.yml
pkg/commands/drift/command.go
pkg/commands/drift/drift.go
pkg/commands/drift/github.go
pkg/commands/plan/plan.go
pkg/github/github.go
pkg/github/github_mock.go

Also fixes #111 
Tested: https://github.com/theteamatx/x-refinery-org/issues/206

feat(drift): Create issues from go

---

.github/workflows/test-admin.yml
.github/workflows/test-apply.yml
pkg/commands/plan/plan_run.go
terraform/has-backend/main.tf
terraform/main.tf

- Add terraform directory for admin and apply
- Add better plan run output

fix: apply not working

---

pkg/commands/entrypoints/entrypoints.go
pkg/git/git.go
pkg/git/git_test.go

fix: entrypoints command diff for deleted files

---

.github/workflows/test-admin.yml
.github/workflows/test-apply.yml
.github/workflows/test-plan.yml
terraform/has-backend/main.tf
terraform/main.tf

chore: update workflows

---

.github/actions/directories/action.yml
terraform/has-backend/main.tf
terraform/main.tf

fix: prevent directories action from matching on comments

---

.github/actions/directories/action.yml
.github/workflows/test-plan.yml
abc.templates/default-workflows/contents/guardian-plan.yml
examples/guardian-plan.yml
terraform/has-backend/main.tf
terraform/main.tf

Recreate https://github.com/abcxyz/guardian/pull/226 because of permissions from fork.

fix: change head.ref and base.ref to .sha

---

pkg/commands/plan/plan_run.go
pkg/commands/plan/plan_run_test.go
pkg/terraform/apply.go
pkg/terraform/format.go
pkg/terraform/format_test.go
pkg/terraform/init.go
pkg/terraform/plan.go
pkg/terraform/show.go
pkg/terraform/terraform.go
pkg/terraform/terraform_mock.go
pkg/terraform/validate.go
pkg/util/util.go

First push should have formatting failure, will fix for merge.

fix: add formatting check to guardian plan

---

.goreleaser.yaml
internal/version/version.go

Fix version injection

---

.github/actions/admin/action.yml
.github/actions/apply/action.yml
.github/actions/plan/action.yml
.github/workflows/lint-test.yml
.github/workflows/test-admin.yml
.github/workflows/test-apply.yml
.github/workflows/test-iam-drift-detection.yml
.github/workflows/test-plan.yml
terraform/no-backend/main.tf

chore: update workflow shas

---

README.md

Will follow up with more in depth details on IAM Drift and Statefile Drift.
Preview: https://github.com/abcxyz/guardian/blob/dcreey/iam-docs/README.md

chore: document guardian features

---

README.md
cli.md

Preview: https://github.com/abcxyz/guardian/blob/dcreey/iam-docs/cli.md
Will follow up with another PR to document the .driftignore file.

chore: document Guardian cli

---

RELEASING.md
abc.templates/base-workflows/contents/guardian-plan.yml
abc.templates/base-workflows/spec.yaml
abc.templates/drift-workflows/spec.yaml

Updating version to create a new release to make abc CLI happy for installation.

fix: base workflow templates and document release process

---

pkg/terraform/terraform.go

Add `force-unlock` to `InitRequiredCommands`

---

.github/workflows/integration.yml

Also refactor integrations tests to store guardian binary upfront end pass to subsequent jobs to improve performance.

fix: explicit permissions in workflow

---

README.md

* Add Support Section
* Add Releases Section
* Add Section describing how to configure git so that private repo terraform modules can be used.

More Documentation Updates

---

README.md

* Updated doc for using `Guardian Admin` worflow.
* Added sections for using `Guardian Run` workflow.

Update docs for Guardian Admin/Run Worflows

---

abc.templates/base-workflows/contents/guardian-admin.yml
abc.templates/base-workflows/contents/guardian-apply.yml
abc.templates/base-workflows/contents/guardian-plan.yml
abc.templates/base-workflows/contents/guardian-run.yml
abc.templates/drift-workflows/contents/guardian-drift-detection.yml

Updated the templates to use the CLI command syntax changes.

Update abc templates

---

README.md

Added documentation about using WIF with guardian.

Add WIF documentation

---

abc.templates/base-workflows/spec.yaml
abc.templates/drift-workflows/spec.yaml

Remove extra `v` from the download URL

---

abc.templates/base-workflows/contents/guardian-admin.yml
abc.templates/base-workflows/contents/guardian-apply.yml
abc.templates/base-workflows/contents/guardian-plan.yml
abc.templates/base-workflows/contents/guardian-run.yml
abc.templates/drift-workflows/contents/guardian-drift-detection.yml

Adds additional support for more recent Terraform version

Update pins of template workflows

---

pkg/commands/cleanup/cleanup.go
pkg/commands/cleanup/cleanup_test.go

We will run this as a step in the plan job:
```
- name: 'Cleanup'
if: always()
run: |-
guardian cleanup -dir="${{ matrix.working_directory }}"
```

refactor: only delete target directory with cleanup

---

abc.templates/base-workflows/contents/guardian-admin.yml

fix: enable quotations in input commands of guardian-admin.yml

---

pkg/commands/cleanup/cleanup.go

Fixes failure here: https://github.com/theteamatx/x-refinery-org/actions/runs/9651619553/job/26619923273?pr=1035

fix: issue where it detects too many entrypoints.

---

.github/workflows/integration.yml
.github/workflows/release.yml
abc.templates/base-workflows/contents/guardian-admin.yml
abc.templates/base-workflows/contents/guardian-apply.yml
abc.templates/base-workflows/contents/guardian-plan.yml
abc.templates/base-workflows/contents/guardian-run.yml
abc.templates/drift-workflows/contents/guardian-drift-detection.yml

Update template actions and workflows

chore: update actions and workflows

---

abc.templates/base-workflows/contents/guardian-admin.yml
abc.templates/base-workflows/contents/guardian-apply.yml
abc.templates/base-workflows/contents/guardian-plan.yml
abc.templates/base-workflows/contents/guardian-run.yml

Move base-workflow permissions to job-level

---

abc.templates/base-workflows/contents/guardian-nightly.yml
abc.templates/base-workflows/contents/guardian-run.yml
abc.templates/base-workflows/spec.yaml

Picks up some of the changes from https://github.com/abcxyz/infra-gcp/pull/1120

Add nightly workflow to abc template, update guardian run

---

.github/workflows/integration.yml

This flag no longer exists in the entrypoint command.

Remove format flag from integration.yml

---

pkg/commands/apply/apply.go
pkg/commands/cleanup/cleanup.go
pkg/commands/iamcleanup/iamcleanup_test.go
pkg/commands/plan/plan.go
pkg/commands/run/run.go
pkg/github/github.go
pkg/terraform/apply.go
pkg/terraform/apply_test.go
pkg/terraform/format.go
pkg/terraform/format_test.go
pkg/terraform/init.go
pkg/terraform/init_test.go
pkg/terraform/plan.go
pkg/terraform/plan_test.go
pkg/terraform/show.go
pkg/terraform/show_test.go
pkg/terraform/terraform_test.go
pkg/terraform/validate.go
pkg/terraform/validate_test.go

Closes https://github.com/abcxyz/guardian/issues/356

fix: use pkg pointer package

---

.github/workflows/integration.yml
.github/workflows/lint-test.yml

fix: add release branches for workflows 

---

pkg/commands/policy/enforce.go
pkg/commands/policy/enforce_test.go
pkg/reporter/github_reporter.go
pkg/reporter/reporter.go

This changes improves the UX for policy enforcement by providing details for policy violations and how to resolve them.

feat: add policy enforcement violations comment

---

abc.templates/base-workflows/contents/workflows/guardian-apply.yml
abc.templates/base-workflows/contents/workflows/guardian-plan.yml
abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-apply.yml
abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-plan.yml

Previous name would print `plan (${{ matrix.directory }})` if the entrypoints array is empty.

Use auto generated matrix job name

---

pkg/platform/github.go
pkg/platform/gitlab.go
pkg/platform/local.go
pkg/platform/platform.go
pkg/platform/platform_mock.go
pkg/platform/reporter.go

Moving all reporter functionality to platform interface. The MockPlatform will be implemented later.

Add CommentEntrypointsSummary to Platform interface with GitHub implementation

---

.github/workflows/integration.yml
pkg/commands/entrypoints/entrypoints.go
pkg/commands/entrypoints/entrypoints_test.go
pkg/commands/entrypoints/testdata/entrypoint1/project1/files/test.txt
pkg/commands/entrypoints/testdata/entrypoint1/project2/files/test.txt
pkg/modifiers/modifiers.go
pkg/modifiers/modifiers_test.go
pkg/platform/github.go
pkg/platform/gitlab.go
pkg/platform/local.go
pkg/platform/platform.go
pkg/platform/platform_mock.go
terraform/project3/.terraform.lock.hcl
terraform/project3/main.tf

NOTE: This will need to be cherry picked into the v2 branch as v3 isnt released yet

feat: add modifiers to allow users to force a directory to be planned/applied

---

pkg/platform/github.go

This was a miss in the v2 branch, but has since been fixed on main (v3). When back porting new functionality to this branch, this bug was discovered. This is mostly copy and paste between main and this branch with some refactoring to missing pieces that exist on main.
- Refactor list pull requests for commit into function (this doesn't need to be in the Platform interface because we aren't adding GitLab functionality into v2, it will exist in v3)
- Fix bug by using the new function in `ReportStatus` and `ReportEntrypointsSummary` to get pull request info when number is missing

fix: fixes entrypoint comments in push

---

abc.templates/base-workflows/contents/workflows/guardian-merge-check.yml
abc.templates/base-workflows/testdata/golden/basic/data/.github/workflows/guardian-merge-check.yml

Updates the mq check to lock the hash of the setup binary action.

fix: lock hashes

---

.github/workflows/ci.yml

These are now on the org level linter.

chore: remove ratchet and actions linters
